#!/usr/bin/expect -f

set force_conservative 0  ;# set to 1 to force conservative mode even if
			  ;# script wasn't run conservatively originally
if {$force_conservative} {
	set send_slow {1 .1}
	proc send {ignore arg} {
		sleep .1
		exp_send -s -- $arg
	}
}

set timeout -1
spawn ./easyrsa sign-req server server
match_max 100000
expect -exact "Type the word 'yes' to continue, or any other input to abort.\r
  Confirm request details: "
send -- "yes\r"
expect eof
