#!/usr/bin/expect -f

set PARAMETER_ONE [lindex $argv 0]

set force_conservative 1  ;# set to 1 to force conservative mode even if
			  ;# script wasn't run conservatively originally
if {$force_conservative} {
	set send_slow {1 .1}
	proc send {ignore arg} {
		sleep .1
		exp_send -s -- $arg
	}
}


set timeout -1
spawn ./slave_ovpn.sh $PARAMETER_ONE
match_max 100000
expect "]:"
send -- "\r"
expect "Confirm request details: "
send -- "yes\r"
expect eof
